name: CI for Node GOAT

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nodegoat:latest

  trufflehog:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified

  sca-snyk:
    runs-on: self-hosted
    needs: [build-and-push, trufflehog]
    steps:
      - uses: actions/checkout@v3
      
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/nodegoat:latest
          args: --file=Dockerfile
      - name: Save Snyk report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sca.sarif
          path: snyk.sarif

  sast-semgrep:
    runs-on: self-hosted
    needs: [build-and-push, trufflehog]

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep for SAST
        uses: returntocorp/semgrep-action@v1
        # with:
          # config: p/security-audit 
          # generateSarif: "true"
      - name: full scan
        run: |
            semgrep \
            --sarif --output semgrep-sast.sarif \
            --metrics=off \
            --config="p/default"

      - name: Upload Semgrep report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sast.sarif
          path: semgrep-sast.sarif
          


